#if DEBUG
import Foundation

/// Redirects the app's on-disk state so a screenshot run reads a checked-in
/// fixture instead of whatever is in the developer's real queue.
///
/// Why this exists: `docs/screenshot.jpg` is a release artifact, regenerated
/// every time the interface changes, and the only way to produce it used to be
/// to point Oxbow at real VODs and photograph the result. That put real
/// streamers' names, titles and thumbnails into an image published on a public
/// README, which is a permission question nobody should have to relitigate for
/// each release. A fixture answers it once.
///
/// **DEBUG only, deliberately.** The hook relocates where the app keeps its
/// queue, which is a reasonable thing for a developer to do and not a thing a
/// shipped build should offer. `#if DEBUG` means it is not merely unused in a
/// release build, it is not compiled into one.
///
/// The seam is `AppComposition.defaultSupportDirectory()`, which is the single
/// place the app decides where its state lives — `resolve` already took the
/// directory as a parameter, so nothing else had to change and no view knows
/// this exists.
///
/// Long-lived by construction: the fixture is the app's own `queue.json`, not
/// a bespoke format, so it is regenerated by copying a real one and rewriting
/// the names (`scripts/screenshots/make-fixture.py`). Nothing here encodes
/// anything about layout, so restyling a view cannot break it.
/// `nonisolated` for the same reason `AppComposition` is: the target defaults
/// new declarations to `@MainActor`, and this is read from
/// `defaultSupportDirectory()`, which is not. It only touches `ProcessInfo`,
/// which is not actor-isolated.
nonisolated enum ScreenshotFixture {

  /// Set to a directory that will stand in for
  /// `~/Library/Application Support/studio.lofti.Oxbow`.
  static let environmentKey = "OXBOW_FIXTURE_DIR"

  /// The fixture directory for this launch, or `nil` for a normal run.
  ///
  /// An empty value counts as unset so that `OXBOW_FIXTURE_DIR=` in a shell
  /// script disables the hook rather than pointing the app at the filesystem
  /// root.
  static var directory: URL? {
    guard
      let path = ProcessInfo.processInfo.environment[environmentKey],
      !path.isEmpty
    else { return nil }
    return URL(filePath: path, directoryHint: .isDirectory)
  }
}
#endif
