#if DEBUG
import AppKit
import Foundation
import SwiftUI

/// Redirects the app's on-disk state so a screenshot run reads a checked-in
/// fixture instead of whatever is in the developer's real queue.
///
/// Why this exists: `docs/screenshot.jpg` is a release artifact, regenerated
/// every time the interface changes, and the only way to produce it used to be
/// to point Oxbow at real VODs and photograph the result. That put real
/// streamers' names, titles and thumbnails into an image published on a public
/// README, which is a permission question nobody should have to relitigate for
/// each release. A fixture answers it once.
///
/// **DEBUG only, deliberately.** The hook relocates where the app keeps its
/// queue, which is a reasonable thing for a developer to do and not a thing a
/// shipped build should offer. `#if DEBUG` means it is not merely unused in a
/// release build, it is not compiled into one.
///
/// The seam is `AppComposition.defaultSupportDirectory()`, which is the single
/// place the app decides where its state lives — `resolve` already took the
/// directory as a parameter, so nothing else had to change and no view knows
/// this exists.
///
/// Long-lived by construction: the fixture is the app's own `queue.json`, not
/// a bespoke format, so it is regenerated by copying a real one and rewriting
/// the names (`scripts/screenshots/make-fixture.py`). Nothing here encodes
/// anything about layout, so restyling a view cannot break it.
/// `nonisolated` for the same reason `AppComposition` is: the target defaults
/// new declarations to `@MainActor`, and this is read from
/// `defaultSupportDirectory()`, which is not. It only touches `ProcessInfo`,
/// which is not actor-isolated.
nonisolated enum ScreenshotFixture {

  /// Set to a directory that will stand in for
  /// `~/Library/Application Support/studio.lofti.Oxbow`.
  static let environmentKey = "OXBOW_FIXTURE_DIR"

  /// The fixture directory for this launch, or `nil` for a normal run.
  ///
  /// An empty value counts as unset so that `OXBOW_FIXTURE_DIR=` in a shell
  /// script disables the hook rather than pointing the app at the filesystem
  /// root.
  static var directory: URL? {
    guard
      let path = ProcessInfo.processInfo.environment[environmentKey],
      !path.isEmpty
    else { return nil }
    return URL(filePath: path, directoryHint: .isDirectory)
  }

  /// A substring of the job title whose row should open its step list.
  ///
  /// Expansion is `@State` inside `JobRow` and deliberately not persisted —
  /// which row a person left open is not queue state. That makes it the one
  /// thing about the screenshot the fixture file cannot express, so it comes
  /// in beside it rather than being faked by clicking at a coordinate, which
  /// is exactly the layout knowledge this harness avoids having.
  static let expandKey = "OXBOW_FIXTURE_EXPAND"

  /// Whether `title` names the row to open. Always false outside a fixture
  /// run, so the variable cannot affect anyone's real queue even in a DEBUG
  /// build.
  static func expandsJob(titled title: String) -> Bool {
    guard directory != nil else { return false }
    guard
      let wanted = ProcessInfo.processInfo.environment[expandKey],
      !wanted.isEmpty
    else { return false }
    return title.contains(wanted)
  }

  /// The content size the queue window should take, as `WIDTHxHEIGHT` in
  /// points.
  ///
  /// Needed because `.defaultSize(width: 720, height: 480)` on that scene does
  /// not get the last word. The queue window has no
  /// `.restorationBehavior(.disabled)`, so AppKit restores its saved frame —
  /// and that frame lives in `UserDefaults`, which `OXBOW_FIXTURE_DIR` does
  /// not redirect. A fixture run therefore inherits whatever size the
  /// developer last left their real window at, and the screenshot is a
  /// different shape on every machine.
  ///
  /// Framing is the one thing a person genuinely should control here — how
  /// much empty room sits under the last row is a design judgement, not a
  /// fact about the data — so it is an input rather than something computed.
  static var windowSize: CGSize? {
    guard directory != nil else { return nil }
    guard let raw = ProcessInfo.processInfo.environment["OXBOW_FIXTURE_SIZE"] else { return nil }
    let parts = raw.lowercased().split(separator: "x")
    guard
      parts.count == 2,
      let width = Double(parts[0]), let height = Double(parts[1]),
      width > 0, height > 0
    else { return nil }
    return CGSize(width: width, height: height)
  }
}

/// Resizes the window hosting it to `ScreenshotFixture.windowSize`.
///
/// AppKit rather than `.defaultSize`, because it has to beat frame
/// restoration, which runs after the scene is built. Applied on the next
/// runloop turn for the same reason `view.window` is nil during `makeNSView`:
/// the view is not in a window yet.
struct ScreenshotWindowSizer: NSViewRepresentable {
  func makeNSView(context: Context) -> NSView {
    let view = NSView(frame: .zero)
    DispatchQueue.main.async {
      guard let window = view.window, let size = ScreenshotFixture.windowSize else { return }
      window.setContentSize(size)
      // Centred so a capture never runs off a screen edge, and so the shot is
      // reproducible on a different display.
      window.center()
    }
    return view
  }

  func updateNSView(_ nsView: NSView, context: Context) {}
}
#endif
