#if DEBUG
import AppKit
import Foundation
import OxbowKit
import SwiftUI

/// Redirects the app's on-disk state so a screenshot run reads a checked-in
/// fixture instead of whatever is in the developer's real queue.
///
/// Why this exists: `docs/screenshot.jpg` is a release artifact, regenerated
/// every time the interface changes, and the only way to produce it used to be
/// to point Oxbow at real VODs and photograph the result. That put real
/// streamers' names, titles and thumbnails into an image published on a public
/// README, which is a permission question nobody should have to relitigate for
/// each release. A fixture answers it once.
///
/// **DEBUG only, deliberately.** The hook relocates where the app keeps its
/// queue, which is a reasonable thing for a developer to do and not a thing a
/// shipped build should offer. `#if DEBUG` means it is not merely unused in a
/// release build, it is not compiled into one.
///
/// The seam is `AppComposition.defaultSupportDirectory()`, which is the single
/// place the app decides where its state lives — `resolve` already took the
/// directory as a parameter, so nothing else had to change and no view knows
/// this exists.
///
/// Long-lived by construction: the fixture is the app's own `queue.json`, not
/// a bespoke format, so it is regenerated by copying a real one and rewriting
/// the names (`scripts/screenshots/make-fixture.py`). Nothing here encodes
/// anything about layout, so restyling a view cannot break it.
/// `nonisolated` for the same reason `AppComposition` is: the target defaults
/// new declarations to `@MainActor`, and this is read from
/// `defaultSupportDirectory()`, which is not. It only touches `ProcessInfo`,
/// which is not actor-isolated.
nonisolated enum ScreenshotFixture {

  /// Set to a directory that will stand in for
  /// `~/Library/Application Support/studio.lofti.Oxbow`.
  static let environmentKey = "OXBOW_FIXTURE_DIR"

  /// The fixture directory for this launch, or `nil` for a normal run.
  ///
  /// An empty value counts as unset so that `OXBOW_FIXTURE_DIR=` in a shell
  /// script disables the hook rather than pointing the app at the filesystem
  /// root.
  static var directory: URL? {
    guard
      let path = ProcessInfo.processInfo.environment[environmentKey],
      !path.isEmpty
    else { return nil }
    return URL(filePath: path, directoryHint: .isDirectory)
  }

  /// A substring of the job title whose row should open its step list.
  ///
  /// Expansion is `@State` inside `JobRow` and deliberately not persisted —
  /// which row a person left open is not queue state. That makes it the one
  /// thing about the screenshot the fixture file cannot express, so it comes
  /// in beside it rather than being faked by clicking at a coordinate, which
  /// is exactly the layout knowledge this harness avoids having.
  static let expandKey = "OXBOW_FIXTURE_EXPAND"

  /// Whether `title` names the row to open. Always false outside a fixture
  /// run, so the variable cannot affect anyone's real queue even in a DEBUG
  /// build.
  static func expandsJob(titled title: String) -> Bool {
    guard directory != nil else { return false }
    guard
      let wanted = ProcessInfo.processInfo.environment[expandKey],
      !wanted.isEmpty
    else { return false }
    return title.contains(wanted)
  }

  /// The content size the queue window should take, as `WIDTHxHEIGHT` in
  /// points.
  ///
  /// Needed because `.defaultSize(width: 720, height: 480)` on that scene does
  /// not get the last word. The queue window has no
  /// `.restorationBehavior(.disabled)`, so AppKit restores its saved frame —
  /// and that frame lives in `UserDefaults`, which `OXBOW_FIXTURE_DIR` does
  /// not redirect. A fixture run therefore inherits whatever size the
  /// developer last left their real window at, and the screenshot is a
  /// different shape on every machine.
  ///
  /// Framing is the one thing a person genuinely should control here — how
  /// much empty room sits under the last row is a design judgement, not a
  /// fact about the data — so it is an input rather than something computed.
  static var windowSize: CGSize? {
    guard directory != nil else { return nil }
    guard let raw = ProcessInfo.processInfo.environment["OXBOW_FIXTURE_SIZE"] else { return nil }
    let parts = raw.lowercased().split(separator: "x")
    guard
      parts.count == 2,
      let width = Double(parts[0]), let height = Double(parts[1]),
      width > 0, height > 0
    else { return nil }
    return CGSize(width: width, height: height)
  }
}

/// The intake's metadata, decoded from `fixture/videoinfo.json`.
///
/// A DTO rather than making `VideoInfo` `Codable`: `VideoInfo` is built by
/// parsing the helper's output and has no reason to round-trip through JSON,
/// and adding a conformance to the shipping model so a screenshot can be taken
/// is the tail wagging the dog. This mirrors only the fields the intake draws.
struct ScreenshotVideoInfo: Decodable {
  struct Quality: Decodable {
    var name: String
    var resolution: String
    var bitsPerSecond: Int
  }

  var streamer: String
  var title: String
  /// ISO 8601. Absolute rather than relative-to-now so the captured date
  /// matches the dates baked into the queue fixture's titles — a composite of
  /// the two windows would otherwise disagree with itself the day after it
  /// was made.
  var createdAt: String
  var durationSeconds: Double
  var qualities: [Quality]
  /// Resolved at run time against the local server the script starts — see
  /// `thumbnailBase`. Twitch's own URLs are absolute, but a fixture's cannot
  /// be: `VideoCard.loadImage` requires an `HTTPURLResponse` with status 200,
  /// so a `file://` URL loads nothing and silently shows the placeholder.
  var thumbnailPaths: [String]

  func resolved(thumbnailBase: URL?) -> VideoInfo {
    VideoInfo(
      streamer: streamer,
      title: title,
      createdAt: ISO8601DateFormatter().date(from: createdAt) ?? .now,
      duration: .seconds(durationSeconds),
      qualities: qualities.map {
        StreamQuality(name: $0.name, resolution: $0.resolution, bitsPerSecond: $0.bitsPerSecond)
      },
      thumbnailURLs: thumbnailBase.map { base in
        thumbnailPaths.map { base.appending(path: $0) }
      } ?? [])
  }
}

extension ScreenshotFixture {

  /// The link the intake opens with, seeded as though it had been pasted.
  static var link: String? {
    guard directory != nil else { return nil }
    let value = ProcessInfo.processInfo.environment["OXBOW_FIXTURE_LINK"]
    return (value?.isEmpty == false) ? value : nil
  }

  /// Whether the intake should open with its trim section down.
  ///
  /// `isTrimExpanded` is model state that `reset()` clears, deliberately —
  /// it is this video's business, not a standing preference, which is exactly
  /// why the options panel *is* a preference and this is not. So it cannot be
  /// set the way the options panel can, through the argument domain.
  static var opensTrim: Bool {
    directory != nil && ProcessInfo.processInfo.environment["OXBOW_FIXTURE_TRIM"] == "1"
  }

  /// The job whose Job Info window should also be opened, if any.
  static var infoJobID: UUID? {
    guard directory != nil else { return nil }
    guard let raw = ProcessInfo.processInfo.environment["OXBOW_FIXTURE_INFO_JOB"], !raw.isEmpty
    else { return nil }
    return UUID(uuidString: raw)
  }

  /// Where the script is serving `fixture/thumbnail.jpg`, e.g.
  /// `http://127.0.0.1:8731`.
  static var thumbnailBase: URL? {
    guard directory != nil else { return nil }
    guard let raw = ProcessInfo.processInfo.environment["OXBOW_FIXTURE_THUMBS"], !raw.isEmpty
    else { return nil }
    return URL(string: raw)
  }

  /// The canned metadata `QueueController.fetchInfo` returns during a fixture
  /// run, so the intake never reaches Twitch for a video that does not exist.
  static var videoInfo: VideoInfo? {
    guard let directory else { return nil }
    let url = directory.appending(path: "videoinfo.json")
    guard
      let data = try? Data(contentsOf: url),
      let decoded = try? JSONDecoder().decode(ScreenshotVideoInfo.self, from: data)
    else { return nil }
    return decoded.resolved(thumbnailBase: thumbnailBase)
  }
}

/// Opens the intake window at launch when the fixture supplies a link.
///
/// The intake is a `Window` scene reached by a menu item or the toolbar `+`,
/// and `.restorationBehavior(.disabled)` means it never comes back on its own.
/// Rather than synthesising a click on the `+` — which would need its
/// coordinates, and so the layout knowledge this harness exists without — the
/// run asks for the window the same way the toolbar button does.
struct ScreenshotIntakeOpener: View {
  @Environment(\.openWindow) private var openWindow
  let windowID: String
  /// Job Info is a `WindowGroup(for: JobID.self)`, so it needs a value rather
  /// than only a scene id — and one naming a job the fixture actually holds.
  let infoWindowID: String

  var body: some View {
    Color.clear
      .frame(width: 0, height: 0)
      .onAppear {
        if let job = ScreenshotFixture.infoJobID {
          openWindow(id: infoWindowID, value: JobID(rawValue: job))
        }
        guard ScreenshotFixture.link != nil else { return }
        openWindow(id: windowID)
        // Deliberately not activating the app.
        //
        // A shell-launched app is not frontmost, so its windows draw inactive:
        // grey traffic lights, and a default button that is not accented. An
        // earlier version called NSApp.activate to fix that, and it worked
        // often enough to look correct -- but macOS does not let an app take
        // focus from whatever the person is actually using, so whether it
        // succeeded depended on what else happened to be running. A capture
        // that is prettier on some machines than others is worse than one that
        // is plainly consistent, and the difference is not only cosmetic: an
        // inactive window gets a smaller shadow, so the composite's geometry
        // moved too.
        //
        // Inactive on purpose, therefore. The layout arithmetic in
        // screenshots.sh derives the shadow inset from the capture, so it
        // stays correct either way.
      }
  }
}

/// Resizes the window hosting it to `ScreenshotFixture.windowSize`.
///
/// AppKit rather than `.defaultSize`, because it has to beat frame
/// restoration, which runs after the scene is built. Applied on the next
/// runloop turn for the same reason `view.window` is nil during `makeNSView`:
/// the view is not in a window yet.
struct ScreenshotWindowSizer: NSViewRepresentable {
  func makeNSView(context: Context) -> NSView {
    let view = NSView(frame: .zero)
    DispatchQueue.main.async {
      guard let window = view.window, let size = ScreenshotFixture.windowSize else { return }
      window.setContentSize(size)
      // Centred so a capture never runs off a screen edge, and so the shot is
      // reproducible on a different display.
      window.center()
    }
    return view
  }

  func updateNSView(_ nsView: NSView, context: Context) {}
}
#endif
